#cloud-config
bootcmd:
 - cloud-init-per instance $(echo "ECS_CLUSTER=${cluster_name}" >> /etc/ecs/ecs.config)

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPIJHj3wu4Q/c+jgeOu19ge7DWLQjCBSoPyDvjucVkYriiHzUtlDK17OF9ynhWOrgHnGQUSRISZ4QHvckCDqYB3d1/wt3GmzqcOyiHfprZ7KbIGM4UrdfIAfkUIyrtVNOXTtz+pG2oADNWK4lyshBRVxD3WiDKHUTSAPYal11oNpePv6b89HNUyA7TNsFwqIeD2j2hHJB7L8KSEydJI3rTbmp0Q6EZFuodasPViQ+0A6eTqm1/LN8dxo3qJLmxxscTABYYUfX0jAJV0+iXwTvswxv++Hlg+sHN/JTffLGbXl2U9DPeUUNnRBrvVezs0vonrTibQuD8y/nklDgyGxvZWNx+qmA53zYF6I8vYFXw0l+5tl6vhp6lCYZbhPnwUlRW9Tl00WmCZNpsnNDNzUOS9h7vAZ1l7s8511w+EOK12wfG/jLJNlHUM1k5g+cuwA3LFRa12cTFa56x4JaALZEqnAOcnY2qeCMfQ1G6r0ObqAorl27tGeb1KZsWc3cLyJNoKGu5DoFo0GfqiyCBS3VuzuC8xDHEVXKN1kv2mLqDA4FmKZKJ8cEPmqRYr6cP7o6FO39sn3nsVaLI4lhA3hBCOAZAQiQdMErlGoA7oLNwNv/iXiqwK4Cya8zPfHIRy5zA9edND6UaATSGxiCOziCEVP9I1AJqS8YIqvoO3cFTRQ== wen.luo@crystalcommerce.com

runcmd:
 - yum install awscli -y
 - aws s3 sync s3://crystalcommerce-${env}-bastionkeys/bastion /tmp/keys
 - touch /home/ec2-user/.ssh/authorized_keys
 - for file in /tmp/keys/*; do cat $file | xargs echo >> /home/ec2-user/.ssh/authorized_keys; done
